"""rolesupp

Revision ID: 03f3c3c8ae54
Revises: 93aba27b3b14
Create Date: 2026-09-16 15:28:58.487781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '03f3c3c8ae54'
down_revision: Union[str, Sequence[str], None] = '93aba27b3b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accident_vehicules', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accident_vehicules', sa.Column('role', mysql.ENUM('fautif', 'victime', 'tiers'), nullable=True))
    # ### end Alembic commands ###
