"""initial schema

Revision ID: 3a504c1f2e1f
Revises: 
Create Date: 2026-02-09 16:15:08.366169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a504c1f2e1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accidents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lieu', sa.String(length=255), nullable=False),
    sa.Column('gravite', sa.Enum('mineur', 'majeur', name='gravite_enum'), nullable=True),
    sa.Column('type', sa.Enum('matériel', 'physique', name='type_accident_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proprietaires',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=False),
    sa.Column('date_permis', sa.Date(), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('aptitude_conduite', sa.Enum('normale', 'réduite', name='aptitude_enum'), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saisons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mois', sa.SmallInteger(), nullable=False),
    sa.Column('periode', sa.Enum('calme', 'fête', 'vacance', name='periode_enum'), nullable=True),
    sa.Column('type', sa.Enum('sec', 'pluvieux', name='type_saison_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('marque', sa.String(length=255), nullable=False),
    sa.Column('modele', sa.String(length=255), nullable=True),
    sa.Column('puissance', sa.BigInteger(), nullable=False),
    sa.Column('cylindre', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Enum('voiture', 'moto', name='type_vehicule_enum'), nullable=True),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.BigInteger(), nullable=False),
    sa.Column('usage', sa.Enum('personnel', 'transport', name='usage_enum'), nullable=True),
    sa.Column('nombre_place', sa.SmallInteger(), nullable=False),
    sa.Column('immatriculation', sa.String(length=255), nullable=True),
    sa.Column('proprietaire_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['proprietaire_id'], ['proprietaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accident_vehicules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('accident_id', sa.BigInteger(), nullable=True),
    sa.Column('vehicule_id', sa.BigInteger(), nullable=True),
    sa.Column('degat', sa.Enum('faible', 'moyen', 'élévé', name='degat_enum'), nullable=True),
    sa.Column('responsabilite', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('fautif', 'victime', 'tiers', name='role_enum'), nullable=True),
    sa.Column('valeur', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['accident_id'], ['accidents.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vehicule_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('tarif', sa.Enum('simple', 'prenium', name='tarif_enum'), nullable=True),
    sa.Column('type_paiement', sa.Enum('annuel', 'semestriel', 'trimestriel', 'mensuel', name='paiement_enum'), nullable=True),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historique_niveau_risks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vehicule_id', sa.BigInteger(), nullable=True),
    sa.Column('saison_id', sa.BigInteger(), nullable=True),
    sa.Column('niveau_risk', sa.Enum('faible', 'moyen', 'élevé', name='niveau_risk_enum'), nullable=True),
    sa.Column('source', sa.Enum('RNA', 'règle', 'PS', name='source_risk_enum'), nullable=True),
    sa.Column('date_evaluation', sa.Date(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['saison_id'], ['saisons.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historique_profils',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vehicule_id', sa.BigInteger(), nullable=True),
    sa.Column('date_evaluation', sa.Date(), nullable=False),
    sa.Column('profil', sa.Enum('prudent', 'normal', 'risqué', name='profil_enum'), nullable=True),
    sa.Column('source', sa.Enum('règle', 'RNA', name='source_profil_enum'), nullable=True),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('plage_deb', sa.Date(), nullable=False),
    sa.Column('plage_fin', sa.Date(), nullable=False),
    sa.Column('contrat_id', sa.BigInteger(), nullable=True),
    sa.Column('frais', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('statut', sa.Boolean(), nullable=False),
    sa.Column('commentaire', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historique_frais',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('frais', sa.BigInteger(), nullable=False),
    sa.Column('historique_niveau_risk_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['historique_niveau_risk_id'], ['historique_niveau_risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historique_frais')
    op.drop_table('factures')
    op.drop_table('historique_profils')
    op.drop_table('historique_niveau_risks')
    op.drop_table('contrats')
    op.drop_table('accident_vehicules')
    op.drop_table('vehicules')
    op.drop_table('saisons')
    op.drop_table('proprietaires')
    op.drop_table('accidents')
    # ### end Alembic commands ###
