"""revenirFacture

Revision ID: 4de0c7ecd287
Revises: 03f3c3c8ae54
Create Date: 2026-09-16 23:08:57.064699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4de0c7ecd287'
down_revision: Union[str, Sequence[str], None] = '03f3c3c8ae54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factures', 'reference')
    op.drop_column('factures', 'mode_paiement')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factures', sa.Column('mode_paiement', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('factures', sa.Column('reference', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
