"""ajout du champ montant dans la table contrats

Revision ID: 84c22cdc80d5
Revises: 7981ba1e7bb9
Create Date: 2026-09-16 12:07:57.582869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '84c22cdc80d5'
down_revision: Union[str, Sequence[str], None] = '7981ba1e7bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrats', sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False))
    op.alter_column('contrats', 'tarif',
               existing_type=mysql.ENUM('basic', 'standard', 'premium'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contrats', 'tarif',
               existing_type=mysql.ENUM('basic', 'standard', 'premium'),
               nullable=False)
    op.drop_column('contrats', 'montant')
    # ### end Alembic commands ###
