"""taillephotopath

Revision ID: 93aba27b3b14
Revises: a7990dc6c569
Create Date: 2026-09-16 14:32:05.495699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93aba27b3b14'
down_revision: Union[str, Sequence[str], None] = 'a7990dc6c569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accidents', 'photo_path',
               existing_type=mysql.VARCHAR(length=500),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accidents', 'photo_path',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
