"""ajout montant contrat

Revision ID: a2b0d8a9c57a
Revises: 7981ba1e7bb9
Create Date: 2026-09-15 20:50:02.327198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b0d8a9c57a'
down_revision: Union[str, Sequence[str], None] = '7981ba1e7bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrats', sa.Column('montant', sa.Numeric(precision=15, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contrats', 'montant')
    # ### end Alembic commands ###
