"""majacc

Revision ID: edb453bc7467
Revises: f6e4ec65943b
Create Date: 2026-09-16 14:13:40.103654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'edb453bc7467'
down_revision: Union[str, Sequence[str], None] = 'f6e4ec65943b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accidents', sa.Column('photo_path', sa.Text(), nullable=True))
    op.alter_column('accidents', 'gravite',
               existing_type=mysql.ENUM('mineur', 'majeur'),
               nullable=False)
    op.alter_column('accidents', 'type',
               existing_type=mysql.ENUM('matériel', 'physique'),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accidents', 'type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('matériel', 'physique'),
               existing_nullable=True)
    op.alter_column('accidents', 'gravite',
               existing_type=mysql.ENUM('mineur', 'majeur'),
               nullable=True)
    op.drop_column('accidents', 'photo_path')
    # ### end Alembic commands ###
