"""Ajout reference et mode_paiement dans factures

Revision ID: f6e4ec65943b
Revises: a2b0d8a9c57a
Create Date: 2026-09-16 07:51:38.646223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e4ec65943b'
down_revision: Union[str, Sequence[str], None] = 'a2b0d8a9c57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factures', sa.Column('reference', sa.String(length=100), nullable=False))
    op.add_column('factures', sa.Column('mode_paiement', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factures', 'mode_paiement')
    op.drop_column('factures', 'reference')
    # ### end Alembic commands ###
